install.packages("gapminder")
library(gapminder)
write.csv(gapminder, "data/gapminder.csv", row.names = FALSE)
file.exists("data/gapminder.csv")
getwd()
list.files()
list.files()
dir.create("data")
list.files()
library(gapminder)
write.csv(gapminder, "data/gapminder.csv", row.names = FALSE)
file.exists("data/gapminder.csv")
